### ISSUE TITLE
new name for repository

### ISSUE THREAD

**Issue by zacharyburnett** [spacetelescope/spacetelescope-env-distribution#22]
`spacetelescope-env-distribution` can be renamed to something more distinct

**Comment by jhunkeler** [comment]
* `stsci-runtime` (it's what you'll use to install your runtime environment)
* `stsci-env` (well, it's definitely an environment)
* `stsci-env-meta` (it provides everything you need for HST, JWST, and whatever else)
* `stsci-snapshot` (it's versioned snapshots of a tested/working environment)
* `stsci-current` (it's providing the current state of affairs at build-time)
* `stsci-dist` (it's distributing software that may not be easy to remember or discover on your own)
* `stsci-lunchbox` ("packing a good lunch is essential")
* `stsci-rolling-release` (still is, kind of)
* `stsci-bakery` (it's giving you "fresh" packages)

**Comment by zacharyburnett** [comment]
Also, @perrygreenfield suggested `rifRAF` and @hbushouse suggested `PINI`

**Comment by zacharyburnett** [comment]
@nden suggested `stcat`

**Comment by zacharyburnett** [comment]
`stcat`:
![8F0086F4-1741-46EC-8BF0-727CD4A2FED2_1_105_c](https://user-images.githubusercontent.com/16024299/182173727-c525aa4f-7148-431a-a6d0-1ea523b330d6.jpeg)

**Comment by nden** [comment]
Paul suggested:

`stenv`

**Comment by nden** [comment]
Paul suggested:

`stdistenv`

**Comment by perrygreenfield** [comment]
Didn't he like stcat the most? But I may misremember.

**Comment by perrygreenfield** [comment]
As for a logo for stcat, a cat with reins on the 3 telescopes....

**Comment by PaulHuwe** [comment]
Logo idea: a cat sleeping on JWST

**Comment by zacharyburnett** [comment]
> Logo idea: a cat sleeping on JWST

A pupil measurement, but there's a silhouette of a sitting cat

**Comment by zacharyburnett** [comment]
Unless anyone has any objections, I made a PR at #32

**Comment by nden** [comment]
I'll make a decision here and go with `stenv`. I think `stcat` is too obscure and too close to `stcal`.
